version: '3'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./data:/var/lib/mysql:rw
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=test123456
          - MYSQL_DATABASE=my_db
        ports:
          - "8082:3306"
  website:
    container_name: php73
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./code:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql 
